# Generated by Django 2.2.12 on 2021-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210806_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('KELLO', 'Kello'), ('KUULUTUS', 'Kuulutus'), ('JÄÄHY', 'Jäähy'), ('PÖYTÄKIRJA', 'Pöytäkirjä'), ('TITU', 'Titu'), ('KUVAAJA', 'Kuvaaja')], default='JÄÄHY', max_length=64, unique=True),
        ),
    ]
